--7
drop VIEW V_POSICION_SORTEO;
drop public SYNONYM V_POSICION_SORTEO;

--6
drop table POSICION_SORTEO;
drop public SYNONYM POSICION_SORTEO;
drop SEQUENCE POSICION_SORTEO_SEQ;
drop public SYNONYM POSICION_SORTEO_SEQ;

--4
drop table SORTEO_CUPO_CONC_AB;
drop public SYNONYM SORTEO_CUPO_CONC_AB;
drop SEQUENCE SORTEO_CUPO_CONC_AB_SEQ;
drop public SYNONYM SORTEO_CUPO_CONC_AB_SEQ;


--3
drop table INSC_CUPO_CONC_ABIERTOS;
drop public SYNONYM INSC_CUPO_CONC_ABIERTOS;
drop SEQUENCE INSC_CUPO_CONC_AB_SEQ;
drop public SYNONYM INSC_CUPO_CONC_AB_SEQ;

--5
drop table SEXO_GENERO_CONC_AB;
drop public SYNONYM SEXO_GENERO_CONC_AB;
drop SEQUENCE SEXO_GENERO_CONC_AB_SEQ;
drop public SYNONYM SEXO_GENERO_CONC_AB_SEQ;

--2
drop table CUPO_CONCURSOS_ABIERTOS;
drop public SYNONYM CUPO_CONCURSOS_ABIERTOS;
drop SEQUENCE CUPO_CONCURSOS_ABIERTOS_SEQ;
drop public SYNONYM CUPO_CONCURSOS_ABIERTOS_SEQ;


-- 1
drop table TIPO_CUPO_CONC_AB;
drop public SYNONYM TIPO_CUPO_CONC_AB;
drop SEQUENCE TIPO_CUPO_CONC_AB_SEQ;
drop public SYNONYM TIPO_CUPO_CONC_AB_SEQ;


drop table CONCURSOS_ABIERTOS;
drop public SYNONYM CONCURSOS_ABIERTOS;
drop SEQUENCE CONCURSOS_ABIERTOS_SEQ;
drop public SYNONYM CONCURSOS_ABIERTOS_SEQ;



