CREATE TABLE CONCURSOS_ABIERTOS
 (ID NUMBER(10) NOT NULL
 ,CODIGO VARCHAR2(50) NOT NULL
 ,DESCRIPCION VARCHAR2(100)
 ,EDAD_TOPE NUMBER(3)
 ,FECHA_DESDE DATE NOT NULL
 ,FECHA_HASTA DATE NOT NULL
 ,CONSTRAINT CONC_AB_PK PRIMARY KEY (ID)
 ,CONSTRAINT CONC_AB_CODIGO_UNIQUE UNIQUE (CODIGO)
  ) ;
  
CREATE PUBLIC SYNONYM CONCURSOS_ABIERTOS FOR ESQBD.CONCURSOS_ABIERTOS;
grant select, insert, update, delete on CONCURSOS_ABIERTOS to USERDB;

CREATE SEQUENCE CONCURSOS_ABIERTOS_SEQ
 START WITH 1
 INCREMENT BY 1
 NOCACHE
 NOCYCLE; 
 
CREATE PUBLIC SYNONYM CONCURSOS_ABIERTOS_SEQ FOR ESQBD.CONCURSOS_ABIERTOS_SEQ;
grant select on CONCURSOS_ABIERTOS_SEQ to USERDB;


CREATE TABLE TIPO_CUPO_CONC_AB
 (ID NUMBER(10) NOT NULL
 ,CODIGO VARCHAR2(50) NOT NULL
 ,DESCRIPCION VARCHAR2(100)
 ,CONSTRAINT TIPO_CUPO_PK PRIMARY KEY (ID)
 ,CONSTRAINT TIPO_CUPO_UNIQUE UNIQUE (CODIGO)
 );
  
CREATE PUBLIC SYNONYM TIPO_CUPO_CONC_AB FOR ESQBD.TIPO_CUPO_CONC_AB;
grant select, insert, update, delete on TIPO_CUPO_CONC_AB to USERDB;

CREATE SEQUENCE TIPO_CUPO_CONC_AB_SEQ
 START WITH 1
 INCREMENT BY 1
 NOCACHE
 NOCYCLE; 
 
CREATE PUBLIC SYNONYM TIPO_CUPO_CONC_AB_SEQ FOR ESQBD.TIPO_CUPO_CONC_AB_SEQ;
grant select on TIPO_CUPO_CONC_AB_SEQ to USERDB;

CREATE TABLE CUPO_CONCURSOS_ABIERTOS
 (ID NUMBER(10) NOT NULL
 ,CODIGO VARCHAR2(50) NOT NULL
 ,DESCRIPCION VARCHAR2(100)
 ,PLAZAS NUMBER(10)
 ,ID_CONCURSOS_ABIERTOS NUMBER(10) NOT NULL
 ,ID_TIPO_CUPO_CONC_AB NUMBER(10) NOT NULL
 ,CONSTRAINT CUPO_CONC_AB_PK PRIMARY KEY (ID)
 ,CONSTRAINT CUPO_CONC_AB_UNIQUE UNIQUE (CODIGO)
 ,CONSTRAINT ID_CONCURSOS_ABIERTOS_FK FOREIGN KEY (ID_CONCURSOS_ABIERTOS) REFERENCES CONCURSOS_ABIERTOS(ID)
 ,CONSTRAINT ID_TIPO_CUPO_CONC_AB_FK FOREIGN KEY (ID_TIPO_CUPO_CONC_AB) REFERENCES TIPO_CUPO_CONC_AB(ID)
);

CREATE PUBLIC SYNONYM CUPO_CONCURSOS_ABIERTOS FOR ESQBD.CUPO_CONCURSOS_ABIERTOS;
grant select, insert, update, delete on CUPO_CONCURSOS_ABIERTOS to USERDB;

CREATE SEQUENCE CUPO_CONCURSOS_ABIERTOS_SEQ
 START WITH 1
 INCREMENT BY 1
 NOCACHE
 NOCYCLE; 
 
CREATE PUBLIC SYNONYM CUPO_CONCURSOS_ABIERTOS_SEQ FOR ESQBD.CUPO_CONCURSOS_ABIERTOS_SEQ;
grant select on CUPO_CONCURSOS_ABIERTOS_SEQ to USERDB;

insert into TIPO_CUPO_CONC_AB(ID,CODIGO, DESCRIPCION) values (TIPO_CUPO_CONC_AB_SEQ.NEXTVAL ,'GENERAL','GENERAL');
insert into TIPO_CUPO_CONC_AB(ID,CODIGO, DESCRIPCION) values (TIPO_CUPO_CONC_AB_SEQ.NEXTVAL ,'AFRODESCENDIENTE','AFRODESCENDIENTE (leyNº19122)');
insert into TIPO_CUPO_CONC_AB(ID,CODIGO, DESCRIPCION) values (TIPO_CUPO_CONC_AB_SEQ.NEXTVAL ,'TRANS','TRANS (ley Nº19684)');

CREATE TABLE SORTEO_CUPO_CONC_AB
 (ID NUMBER(10) NOT NULL
 ,SEMILLA NUMBER(10) NOT NULL
 ,FECHA_SORTEO TIMESTAMP(6) NOT NULL
 ,ID_CUPO_CONC_AB  NUMBER(10) NOT NULL
 ,CONSTRAINT SORTEO_CUPO_CONC_AB_PK PRIMARY KEY (ID)
 ,CONSTRAINT ID_CUPO_CONC_AB_S_UNIQUE UNIQUE (ID_CUPO_CONC_AB)
 ,CONSTRAINT ID_CUPO_CONC_AB_S_FK FOREIGN KEY (ID_CUPO_CONC_AB) REFERENCES CUPO_CONCURSOS_ABIERTOS(ID)
);

CREATE PUBLIC SYNONYM SORTEO_CUPO_CONC_AB FOR ESQBD.SORTEO_CUPO_CONC_AB;
grant select, insert, update, delete on SORTEO_CUPO_CONC_AB to USERDB;

CREATE SEQUENCE SORTEO_CUPO_CONC_AB_SEQ
 START WITH 1
 INCREMENT BY 1
 NOCACHE
 NOCYCLE; 
 
CREATE PUBLIC SYNONYM SORTEO_CUPO_CONC_AB_SEQ FOR ESQBD.SORTEO_CUPO_CONC_AB_SEQ;
grant select on SORTEO_CUPO_CONC_AB_SEQ to USERDB;


CREATE TABLE SEXO_GENERO_CONC_AB
 (ID NUMBER(10) NOT NULL
 ,DESCRIPCION VARCHAR2(100)
 ,CONSTRAINT SEXO_GENERO_CONC_AB_PK PRIMARY KEY (ID)
 );
 
CREATE PUBLIC SYNONYM SEXO_GENERO_CONC_AB FOR ESQBD.SEXO_GENERO_CONC_AB;
grant select, insert, update, delete on SEXO_GENERO_CONC_AB to USERDB;

CREATE SEQUENCE SEXO_GENERO_CONC_AB_SEQ
 START WITH 1
 INCREMENT BY 1
 NOCACHE
 NOCYCLE; 
 
CREATE PUBLIC SYNONYM SEXO_GENERO_CONC_AB_SEQ FOR ESQBD.SEXO_GENERO_CONC_AB_SEQ;
grant select on SEXO_GENERO_CONC_AB_SEQ to USERDB;

insert into SEXO_GENERO_CONC_AB(ID,DESCRIPCION) values (SEXO_GENERO_CONC_AB_SEQ.NEXTVAL ,'MUJER');
insert into SEXO_GENERO_CONC_AB(ID,DESCRIPCION) values (SEXO_GENERO_CONC_AB_SEQ.NEXTVAL ,'HOMBRE');
insert into SEXO_GENERO_CONC_AB(ID,DESCRIPCION) values (SEXO_GENERO_CONC_AB_SEQ.NEXTVAL ,'MUJER TRANS');
insert into SEXO_GENERO_CONC_AB(ID,DESCRIPCION) values (SEXO_GENERO_CONC_AB_SEQ.NEXTVAL ,'HOMBRE TRANS');
insert into SEXO_GENERO_CONC_AB(ID,DESCRIPCION) values (SEXO_GENERO_CONC_AB_SEQ.NEXTVAL ,'OTROS');

CREATE TABLE INSC_CUPO_CONC_ABIERTOS
 (
  ID NUMBER(10) NOT NULL
 ,CI NUMBER(10) NOT NULL
 ,CI_BARRA NUMBER(1) NOT NULL
 ,PRIMER_NOMBRE VARCHAR2(50) NOT NULL
 ,SEGUNDO_NOMBRE VARCHAR2(50)
 ,PRIMER_APELLIDO VARCHAR2(50) NOT NULL
 ,SEGUNDO_APELLIDO VARCHAR2(50)
 ,FECHA_NACIMIENTO TIMESTAMP(6) NOT NULL
 ,TELEFONO_CONTACTO VARCHAR2(20) NOT NULL
 ,TELEFONO_CELULAR VARCHAR2(20)
 ,CORREO_ELECTRONICO VARCHAR2(50) NOT NULL
 ,DIRECCION VARCHAR(100) NOT NULL
 ,ID_SEXO_GENERO NUMBER(10) NOT NULL
 ,ID_CUPO_CONC_AB NUMBER(10) NOT NULL
 ,FECHA_INSCRIPCION TIMESTAMP(6) NOT NULL
 ,NUMERO_INSCRIOPCION NUMBER(7) NOT NULL
 ,TOKEN VARCHAR(30) NOT NULL
 ,ELIMINADA NUMBER(1)
 ,FECHA_ELIMINADA TIMESTAMP(6)
 ,CONSTRAINT NUM_INSC_CUPO_UNIQUE UNIQUE (ID_CUPO_CONC_AB,NUMERO_INSCRIOPCION)
 ,CONSTRAINT INSC_CUPO_CONC_AB_PK PRIMARY KEY (ID)
 ,CONSTRAINT ID_CUPO_CONC_FK FOREIGN KEY (ID_CUPO_CONC_AB) REFERENCES CUPO_CONCURSOS_ABIERTOS(ID)
 ,CONSTRAINT ID_SEXO_GENERO_FK FOREIGN KEY (ID_SEXO_GENERO) REFERENCES SEXO_GENERO_CONC_AB(ID)
);

CREATE PUBLIC SYNONYM INSC_CUPO_CONC_ABIERTOS FOR ESQBD.INSC_CUPO_CONC_ABIERTOS;
grant select, insert, update, delete on INSC_CUPO_CONC_ABIERTOS to USERDB;
CREATE SEQUENCE INSC_CUPO_CONC_AB_SEQ
 START WITH 1
 INCREMENT BY 1
 NOCACHE
 NOCYCLE; 
CREATE PUBLIC SYNONYM INSC_CUPO_CONC_AB_SEQ FOR ESQBD.INSC_CUPO_CONC_AB_SEQ;
grant select on INSC_CUPO_CONC_AB_SEQ to USERDB;


CREATE TABLE POSICION_SORTEO
 (ID NUMBER(10) NOT NULL
 ,POSICION NUMBER(6) NOT NULL
 ,ID_INSC_CUPO_CONC_AB NUMBER(10) NOT NULL
 ,ID_SORTEO_CUPO_CONC_AB NUMBER(10) NOT NULL
 ,CONSTRAINT POSICION_SORTEO_PK PRIMARY KEY (ID)
 ,CONSTRAINT ID_INSC_CUPO_CONC_AB_FK FOREIGN KEY (ID_INSC_CUPO_CONC_AB) REFERENCES INSC_CUPO_CONC_ABIERTOS(ID)
 ,CONSTRAINT ID_SORTEO_CUPO_CONC_AB_FK FOREIGN KEY (ID_SORTEO_CUPO_CONC_AB) REFERENCES SORTEO_CUPO_CONC_AB(ID)
);


CREATE PUBLIC SYNONYM POSICION_SORTEO FOR ESQBD.POSICION_SORTEO;
grant select, insert, update, delete on POSICION_SORTEO to USERDB;

CREATE SEQUENCE POSICION_SORTEO_SEQ
 START WITH 1
 INCREMENT BY 1
 NOCACHE
 NOCYCLE; 
 
CREATE PUBLIC SYNONYM POSICION_SORTEO_SEQ FOR ESQBD.POSICION_SORTEO_SEQ;
grant select on POSICION_SORTEO_SEQ to USERDB;

CREATE OR REPLACE VIEW V_POSICION_SORTEO(ID_SORTEO, POSICION, NUMERO_INSCRIPCION, CI, CI_BARRA, PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLLIDO, FECHA_NACIMIENTO,TELEFONO,CELULAR,CORREO,FECHA_INSCRIPCION) AS
select 
    pos.id_sorteo_cupo_conc_ab
    ,pos.posicion
    ,insc.NUMERO_INSCRIOPCION
    ,insc.CI
    ,insc.CI_BARRA
    ,insc.PRIMER_NOMBRE
    ,insc.SEGUNDO_NOMBRE
    ,insc.PRIMER_APELLIDO
    ,insc.SEGUNDO_APELLIDO
    ,insc.FECHA_NACIMIENTO
    ,insc.TELEFONO_CONTACTO
    ,insc.TELEFONO_CELULAR
    ,insc.CORREO_ELECTRONICO
    ,insc.FECHA_INSCRIPCION
from insc_cupo_conc_abiertos insc, posicion_sorteo pos 
WHERE pos.id_insc_cupo_conc_ab=insc.id;

CREATE PUBLIC SYNONYM V_POSICION_SORTEO FOR ESQBD.V_POSICION_SORTEO;
grant select on V_POSICION_SORTEO to USERDB;
